### ISSUE TITLE
Failed to run CLI create

### ISSUE THREAD

**Issue by johnson86tw** [chnejohnson/maci#5]
```
root@e2459b41a2dd:~/maci/cli# node build create
Deploying InitialVoiceCreditProxy
Deploying Poseidon contracts
Linking Poseidon libraries to MACI
Linking Poseidon libraries to PollFactory
Linking Poseidon libraries to MessageAqFactory
Deploying MACI
Transferring PollFactory ownership to MACI
Transferring MessageAqFactory ownership to PollFactory
Initialising MACI
(node:450) UnhandledPromiseRejectionWarning: ProviderError: Error: Transaction reverted: function selector was not recognized and there's no fallback function
    at HttpProvider.request (/root/maci/contracts/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
    at LocalAccountsProvider.request (/root/maci/contracts/node_modules/hardhat/src/internal/core/providers/accounts.ts:187:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at EthersProviderWrapper.send (/root/maci/cli/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:450) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:450) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by johnson86tw** [comment]
should deploy vkRegistry contract at first:
```
> node build deployVkRegistry
VkRegistry: 0x82D50AD3C1091866E258Fd0f1a7cC9674609D254

> node build create -r 0x82D50AD3C1091866E258Fd0f1a7cC9674609D254
```
